services:
  node_app:
    build: .
    image: centrals:latest
    container_name: centrals

    ports:
      - "3000:3000"

    environment:
      NODE_ENV: production
      DB_HOST: mariadb_db       # connects if DB exists on network
      DB_USER: root
      DB_PASSWORD: rootpassword
      DB_NAME: fyish_01
      REDIS_HOST: redis-container
      REDIS_PORT: 6379
      KAFKA_BROKER: kafka:9092
      JWTKEY: SECRETKEY
      SIGNATURE_SECRET: HAPPYHOURS
      BCRYPT_SECRET_KEY: LARGEMACHINE
      JWT_SECRET: MAXSTADIUM
      MAILER_URL: http://mailing:3014/
      REFRESHTOKEN_KEY: ROLLERGOSTER

    networks:
      - database_network
      - app_net

    restart: always

networks:
  app_net:
    external: true

  database_network:
    driver: bridge






     